version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=dev
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 1s
      timeout: 20s
      retries: 10
